name: video-downloader
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: video-downloader-app
        restart: always
        env_file:
            - .env
        volumes:
            - ./src:/app/src
            - ./public:/app/public
            - ./views:/app/views
            - ./logs:/tmp/logs
        depends_on:
            - nginx
        networks:
            - downloader-net
        cpus: 2
        mem_limit: 4g
    nginx:
        image: nginx:1.27-alpine
        container_name: video-downloader-nginx
        restart: always
        ports:
            - '83:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./public:/app/public:ro
        networks:
            - downloader-net
        cpus: 1
        mem_limit: 512m
networks:
    downloader-net:
        driver: bridge
